apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-oaos
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-oaos
    app.kubernetes.io/part-of: ci1t-830-0095-app
  name: devfile-sample-oaos
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-oaos
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-oaos
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0095-tenant/ci1t-830-0095-app/devfile-sample-oaos@sha256:f8fd8a8b9b6170d0445a3cf4e40e5601c220ab54b84853bbc5c187b075efeedd
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
