apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-oaos
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0095-tenant/ci1t-830-0095-app/devfile-sample-oaos@sha256:f8fd8a8b9b6170d0445a3cf4e40e5601c220ab54b84853bbc5c187b075efeedd
        name: my-nodejs
        resources: {}
status: {}
